### ISSUE TITLE
Double Datepickers when used together with Better Post UI

### ISSUE THREAD

**Issue by perifer** [helsingborg-stad/content-scheduler#1]
5403e9c9dfe15196e7c18bf25b0b6912a1c46aee removed CSS but left `Publish.js` that initialises the datepicker. This leads to double datepickers when Better Post UI is activated.

Somewhat related: the upbublish datepicker still initialized in content scheduler looses some styling when Better Post UI is not active (since you moved all the CSS) - it still works ok though in my tests. One could argue that Better Post UI should enhance the Content schedulers unpublish field as well, but maybe that is tricky and leads to unwanted dependencies.

**Comment by Svanmark** [comment]
Thanks. I'll look into this.
